### ISSUE TITLE
Move callback creation into plans

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/python-artemis#659] opened 2023-05-15 15:25 UTC
In some cases, a plan may need to do something to get information before callbacks are instantiated. Also, callbacks can be specific to the plan. therefore, they should be managed by the plan, probably in `get_plan`

**Comment by DominicOram** [comment] 2023-05-15 15:57
Duplicate of https://github.com/DiamondLightSource/python-artemis/issues/656

**Closed by DominicOram** 2023-05-15 15:57 UTC
