### ISSUE TITLE
Put z steps back to 0 at the end of scan

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/python-artemis#243] opened 2022-10-04 12:07 UTC
After having run Artemis I would like the next scan to by default be 2D as it may be being run by GDA. To do this we need to set the z steps to zero at the end of the plan.

## Acceptance Criteria
* The z steps are always set to zero at the end of a plan
* This happens regardless of the success/failure of the plan

**Comment by bentom08** [comment] 2022-10-13 12:59
Closing this as a duplicate of this ticket - https://github.com/DiamondLightSource/python-artemis/issues/114

**Closed by bentom08** 2022-10-13 12:59 UTC
Labels: needed_for_release
